- project:
    templates:
      - check-requirements
      - openstack-lower-constraints-jobs
      - openstack-python3-ussuri-jobs
      - openstackclient-plugin-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
